; PlatformIO configuration for running examples

[env]
lib_deps =
    fortyseveneffects/MIDI Library@^5.0.2
build_flags =
    -D REMIDI_DEBUG=1
    -D REMIDI_DEBUG_SERIAL=Serial

; Environment for example project `tapedelay`
; This is a real project using an Arduino Pro Micro
[env:tapedelay]
platform = atmelavr
board = micro
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<*>
    +<../examples/tapedelay/>

[env:tapedelay_uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<*>
    +<../examples/tapedelay/>
build_flags =
    -D REMIDI_DEBUG=1
    -D REMIDI_DEBUG_SERIAL=Serial
    -D REMIDI_SERIAL_MIDI_TEST=0


; --------------------------- Testing environments --------------------------- ;
; Testing on real Arduino UNO
[env:test_uno]
platform = atmelavr
board = uno
framework = arduino
test_build_src = true
test_filter =
    common/*
    avr/*

; Testing on Arduino UNO using `avrsim`
; Please run this test environment with `--without-uploading`
[env:test_uno_sim]
platform = atmelavr
board = uno
framework = arduino
test_build_src = true
test_filter =
    common/*
    avr/*
platform_packages =
    platformio/tool-simavr
test_speed = 9600
test_testing_command =
    ${platformio.packages_dir}/tool-simavr/bin/simavr
    -m
    atmega328p
    -f
    16000000L
    ${platformio.build_dir}/${this.__env__}/firmware.elf

; Testing on native
[env:test_native]
platform = native
test_build_src = true
test_filter =
    common/*
    native/*