; PlatformIO configuration for running examples

[env]
lib_deps =
    fortyseveneffects/MIDI Library@^5.0.2

[env:tapedelay]
platform = atmelavr
board = micro
framework = arduino
build_src_filter =
    +<*> +<../examples/tapedelay/>

[env:test_avr]
platform = atmelavr
board = uno
framework = arduino
test_build_src = true
test_filter =
    common
    avr

[env:test_native]
platform = native
test_build_src = true
test_filter =
    common/*
    native/*